version: '3.8'

services:
  sismes:
    container_name: sismes
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
