[supabase]
BUCKET = "seismograms"

[colors]
YESTERDAY = "#a3abbd"
TODAY = "#802644"

[stations]

  [stations.PAND]
  name="PAND"
  client="RESIF"
  network="FR"
  location="00"
  channel="HHZ"
  amplification=500000

  [stations.SCOL]
  name="SCOL"
  client="ICGC"
  network="CA"
  location=""
  channel="HNZ"
  amplification=8000

  [stations.ARBS]
  name="ARBS"
  client="ICGC"
  network="CA"
  location=""
  channel="HH1"
  amplification=1000
